# Generated by Django 4.1 on 2022-08-18 23:43

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path)),
                ('small_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('no_discount_price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
